# Generated by Django 4.2.1 on 2023-05-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
